-- 팀에서 확정한 MySQL 스키마 (수신본 원문)
--
-- core/models.py 는 이 파일을 그대로 미러링합니다. 모델은 전부 managed=False 이며
-- Django 는 이 테이블들을 읽기만 합니다. 스키마 변경은 이 파일을 통해서만 일어납니다.
-- 보완 제안은 proposed-alter.sql 을 보세요.
--
-- 이 백엔드가 실제로 읽는 테이블은 7개입니다:
--   MAIN_BANNER, POPUP, POPUP_I18N, FESTIVAL, FESTIVAL_I18N, PLACE, CATEGORY
-- 나머지는 다른 팀원 담당이며 참고용으로 함께 보관합니다.

CREATE TABLE USERS (
    NO INT NOT NULL AUTO_INCREMENT COMMENT '사용자 NO',
    ID VARCHAR(100) NOT NULL COMMENT '사용자 고유 ID',
    NICKNAME VARCHAR(100) NOT NULL COMMENT '사용자 닉네임',
    COUNTRY VARCHAR(100) NOT NULL COMMENT '국가',
    BIRTH_DATE DATE DEFAULT NULL COMMENT '생년월일',
    EMAIL VARCHAR(255) NOT NULL COMMENT '이메일',
    PROFILE_IMAGE VARCHAR(500) DEFAULT NULL COMMENT '프로필 이미지 URL',
    STATUS TINYINT NOT NULL DEFAULT 1 COMMENT '회원 상태 (1: 사용중, 2: 휴면, 3: 탈퇴)',
    LANGUAGE_CODE VARCHAR(10) NOT NULL DEFAULT 'ko' COMMENT '언어 코드',
    LAST_VISITED_AT TIMESTAMP NULL DEFAULT NULL COMMENT '최근 방문일시',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    DELETED_AT TIMESTAMP NULL DEFAULT NULL COMMENT '탈퇴일시',
    PRIMARY KEY (NO),
    UNIQUE KEY UK_USERS_ID (ID)
) COMMENT='사용자 정보 테이블';

CREATE TABLE USER_AUTH (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '인증 정보 순번',
    USER_NO INT NOT NULL COMMENT '사용자 고유 NO',
    PASSWORD_HASH VARCHAR(255) DEFAULT NULL COMMENT '비밀번호 해시',
    PROVIDER TINYINT NOT NULL DEFAULT 1 COMMENT '로그인 방식 (1: 일반, 2: Google, 3: Kakao, 4: Naver)',
    PROVIDER_ID VARCHAR(255) DEFAULT NULL COMMENT '소셜 로그인 제공자 사용자 ID',
    EMAIL_VERIFIED TINYINT NOT NULL DEFAULT 0 COMMENT '이메일 인증 여부 (0: 미인증, 1: 인증)',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    PRIMARY KEY (IDX),
    CONSTRAINT FK_USER_AUTH_USERS FOREIGN KEY (USER_NO) REFERENCES USERS(NO) ON DELETE CASCADE
) COMMENT='사용자 인증 정보 테이블';

CREATE TABLE USER_CHARACTER (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '사용자 캐릭터 순번',
    USER_NO INT NOT NULL COMMENT '사용자 순번',
    CHARACTER_IDX INT NOT NULL COMMENT '착용 가능 캐릭터 IDX',
    IS_SELECTED TINYINT NOT NULL DEFAULT 0 COMMENT '대표 캐릭터 여부 (0: 미선택, 1: 선택)',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    PRIMARY KEY (IDX),
    CONSTRAINT FK_USER_CHARACTER_USERS FOREIGN KEY (USER_NO) REFERENCES USERS(NO) ON DELETE CASCADE
) COMMENT='사용자 캐릭터 테이블';

CREATE TABLE USER_ITEM (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '사용자 아이템 순번',
    USER_NO INT NOT NULL COMMENT '사용자 고유 NO',
    USER_CHARACTER_IDX INT NOT NULL COMMENT '사용자 캐릭터 순번 USER_CARACTER IDX',
    ITEM_IDX INT NOT NULL COMMENT '아이템 순번 ITEM IDX',
    IS_EQUIPPED TINYINT NOT NULL DEFAULT 0 COMMENT '착용 여부 (0: 미착용, 1: 착용)',
    ACQUIRED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '획득일시',
    PRIMARY KEY (IDX)
) COMMENT='사용자 아이템 테이블';

CREATE TABLE ITEM (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '아이템 IDX',
    ITEM_NAME VARCHAR(100) NOT NULL COMMENT '아이템명',
    ITEM_TYPE TINYINT NOT NULL COMMENT '아이템 종류 (1: 모자, 2: 상의, 3: 하의, 4: 신발, 5: 무기, 6: 장신구)',
    CHARACTER_IDX INT NOT NULL COMMENT '착용 가능 캐릭터 IDX',
    ITEM_IMAGE VARCHAR(255) DEFAULT NULL COMMENT '아이템 이미지',
    ITEM_MODEL_IMAGE VARCHAR(255) DEFAULT NULL COMMENT '아이템 모델 이미지',
    ITEM_DESCRIPTION VARCHAR(500) DEFAULT NULL COMMENT '아이템 설명',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    PRIMARY KEY (IDX)
) COMMENT='아이템 마스터 테이블';

CREATE TABLE CHARACTER_MASTER (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '캐릭터 순번',
    CHARACTER_TYPE VARCHAR(100) NOT NULL COMMENT '캐릭터 타입 (1: 승려, 2: 궁녀, 3: 왕, 4: 상인, 5: 무사)',
    IMAGE_URL VARCHAR(255) DEFAULT NULL COMMENT '캐릭터 이미지',
    IS_ACTIVE TINYINT NOT NULL DEFAULT 1 COMMENT '사용 여부 (0: 미사용, 1: 사용)',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    PRIMARY KEY (IDX)
) COMMENT='캐릭터';

CREATE TABLE MAIN_BANNER (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '인덱스',
    IMG VARCHAR(800) DEFAULT NULL COMMENT '이미지 URL',
    START_DATE DATETIME DEFAULT NULL COMMENT '시작날짜',
    END_DATE DATETIME DEFAULT NULL COMMENT '끝나는날짜',
    IS_DISPLAY TINYINT NOT NULL DEFAULT 0 COMMENT '전시여부 (0: 비노출, 1: 노출)',
    IS_TRASH TINYINT NOT NULL DEFAULT 0 COMMENT '삭제여부 (0: 사용, 1: 삭제)',
    LINK VARCHAR(800) DEFAULT NULL COMMENT '링크',
    SORT INT NOT NULL DEFAULT 0 COMMENT '노출순서',
    TITLE VARCHAR(300) DEFAULT NULL COMMENT '타이틀',
    SUB_TITLE VARCHAR(200) DEFAULT NULL COMMENT '서브타이틀',
    PRIMARY KEY (IDX)
) COMMENT='메인배너';

CREATE TABLE POPUP (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '인덱스',
    TITLE VARCHAR(1000) DEFAULT NULL COMMENT '타이틀',
    CONTENT TEXT DEFAULT NULL COMMENT '내용',
    IMG VARCHAR(500) DEFAULT NULL COMMENT '이미지',
    LINK VARCHAR(500) DEFAULT NULL COMMENT '링크',
    START_DATE DATETIME DEFAULT NULL COMMENT '시작날짜',
    END_DATE DATETIME DEFAULT NULL COMMENT '끝나는날짜',
    IS_DISPLAY TINYINT NOT NULL DEFAULT 0 COMMENT '전시여부 (0: 비노출, 1: 노출)',
    PRIMARY KEY (IDX)
) COMMENT='팝업/공지사항';

CREATE TABLE CATEGORY (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '인덱스',
    TYPE VARCHAR(100) NOT NULL COMMENT '종류 (TOUR, FOOD)',
    CATEGORY_DIV VARCHAR(100) NOT NULL COMMENT '구분 (TOUR: 문화재 자연 , FOOD: 한식 카페)',
    CONTENT VARCHAR(600) DEFAULT NULL COMMENT '설명',
    IS_DISPLAY TINYINT NOT NULL DEFAULT 0 COMMENT '전시여부 (0: 비노출, 1: 노출)',
    REG_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
    PRIMARY KEY (IDX)
) COMMENT='카테고리';

CREATE TABLE FESTIVAL (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '인덱스',
    NAME VARCHAR(300) DEFAULT NULL COMMENT '페스티벌 제목',
    CONTENT VARCHAR(700) DEFAULT NULL COMMENT '내용',
    LOCATION VARCHAR(500) DEFAULT NULL COMMENT '장소',
    START_DATE DATETIME DEFAULT NULL COMMENT '시작날짜',
    IMG VARCHAR(600) DEFAULT NULL COMMENT '이미지',
    URL VARCHAR(600) DEFAULT NULL COMMENT 'URL',
    IS_TRASH TINYINT NOT NULL DEFAULT 0 COMMENT '삭제여부 (0: 사용, 1: 삭제)',
    END_DATE DATETIME DEFAULT NULL COMMENT '끝나는날짜',
    PRIMARY KEY (IDX)
) COMMENT='축제';

CREATE TABLE PLACE(
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '인덱스',
    CATEGORY_IDX INT NOT NULL COMMENT '카테고리 IDX',
    NAME VARCHAR(200) DEFAULT NULL COMMENT '관광지명',
    TEXT TEXT DEFAULT NULL COMMENT '소개',
    ADDRESS VARCHAR(500) DEFAULT NULL COMMENT '주소',
    LATITUDE VARCHAR(50) DEFAULT NULL COMMENT '위도',
    LONGITUDE VARCHAR(50) DEFAULT NULL COMMENT '경도',
    OPERATING_HOURS VARCHAR(300) DEFAULT NULL COMMENT '운영시간',
    ADMISSION_FEE VARCHAR(300) DEFAULT NULL COMMENT '입장료',
    PARKING VARCHAR(300) DEFAULT NULL COMMENT '주차여부',
    IS_RECOMMENDED TINYINT NOT NULL DEFAULT 0 COMMENT '메인추천여부 (0: 미추천, 1: 추천)',
    VIEW_COUNT INT NOT NULL DEFAULT 0 COMMENT '조회수',
    REG_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
    PRIMARY KEY (IDX)
) COMMENT='관광지/맛집 리스트';

CREATE TABLE SPOTS (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '스팟 게시글 순번',
    USER_NO INT NOT NULL COMMENT '작성자 NO',
    MAP_PLACE_ID VARCHAR(255) DEFAULT NULL COMMENT '장소 ID',
    LAT DECIMAL(9,6) NOT NULL COMMENT '위도',
    LNG DECIMAL(9,6) NOT NULL COMMENT '경도',
    PHOTO_URL VARCHAR(500) DEFAULT NULL COMMENT '사진 URL',
    CAPTION VARCHAR(350) DEFAULT NULL COMMENT '한줄평',
    LIKE_COUNT INT NOT NULL DEFAULT 0 COMMENT '좋아요 수',
    MODERATION_STATUS TINYINT NOT NULL DEFAULT 0 COMMENT '검증상태 (0: 대기, 1: 승인, 2: 거절)',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    DELETED_AT TIMESTAMP NULL DEFAULT NULL COMMENT '삭제일시',
    PRIMARY KEY (IDX)
) COMMENT='스팟 게시글';

CREATE TABLE SPOT_COMMENT (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '댓글 순번',
    SPOT_IDX INT NOT NULL COMMENT '스팟 게시글 순번',
    USER_NO INT NOT NULL COMMENT '사용자 고유 NO',
    CONTENT TEXT NOT NULL COMMENT '댓글 내용',
    MODERATION_STATUS TINYINT NOT NULL DEFAULT 0 COMMENT '검증상태 (0: 대기, 1: 승인, 2: 거절)',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    PRIMARY KEY (IDX)
) COMMENT='스팟 댓글';

CREATE TABLE SPOT_REACTIONS (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '리액션 순번',
    SPOT_IDX INT NOT NULL COMMENT '스팟 게시글 순번',
    USER_NO INT NOT NULL COMMENT '사용자 고유 NO',
    TYPE TINYINT NOT NULL COMMENT '타입 (1: 좋아요, 2: 북마크)',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    PRIMARY KEY (IDX)
) COMMENT='스팟 반응(좋아요,북마크)';

CREATE TABLE MAP_PLACE_DOCENT (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '도슨트 순번',
    MAP_PLACE_IDX INT NOT NULL COMMENT '장소 순번',
    LANGUAGE_CODE VARCHAR(10) NOT NULL COMMENT '언어 코드(ko, en, ja, zh)',
    TITLE VARCHAR(200) NOT NULL COMMENT '도슨트 제목',
    CONTENT TEXT NOT NULL COMMENT '도슨트 본문 내용',
    DESCRIPTION TEXT DEFAULT NULL COMMENT '도슨트 부가설명',
    AUDIO_URL VARCHAR(1000) DEFAULT NULL COMMENT '음성 파일 URL',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UNIQUE KEY UK_MAP_PLACE_LANGUAGE (MAP_PLACE_IDX, LANGUAGE_CODE),
    PRIMARY KEY (IDX)
) COMMENT='장소별 다국어 도슨트 정보';

CREATE TABLE COURSE (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '코스 IDX',
    USER_CHARACTER_IDX INT NOT NULL COMMENT '사용자 캐릭터 IDX',
    COURSE_NAME VARCHAR(100) NOT NULL COMMENT '코스명',
    DESCRIPTION VARCHAR(500) DEFAULT NULL COMMENT '코스 설명',
    COURSE_IMAGE VARCHAR(255) DEFAULT NULL COMMENT '코스 이미지',
    REWARD_IMAGE VARCHAR(500) NOT NULL DEFAULT 0 COMMENT '코스 완료 보상 이미지',
    IS_ACTIVE TINYINT NOT NULL DEFAULT 1 COMMENT '사용 여부 (0: 미사용, 1: 사용)',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX)
) COMMENT='코스';

CREATE TABLE QUEST (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '퀘스트 순번',
    COURSE_IDX INT NOT NULL COMMENT '코스 순번',
    MAP_PLACE_IDX INT NOT NULL COMMENT '장소 순번',
    QUEST_ORDER TINYINT NOT NULL COMMENT '퀘스트 순서',
    QUEST_TYPE TINYINT NOT NULL COMMENT '퀘스트 종류 (1: 방문, 2: 사진촬영, 3: 도슨트청취, 4: 퀴즈)',
    TITLE VARCHAR(200) NOT NULL COMMENT '퀘스트 제목',
    CONTENT TEXT DEFAULT NULL COMMENT '퀘스트 설명',
    REWARD_ITEM_IDX INT DEFAULT NULL COMMENT '퀘스트 보상 아이템 ITEM IDX',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX)
) COMMENT='퀘스트';

CREATE TABLE USER_QUEST (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '사용자 퀘스트 순번',
    USER_CHARACTER_IDX INT NOT NULL COMMENT '사용자 캐릭터 순번',
    QUEST_IDX INT NOT NULL COMMENT '퀘스트 순번',
    STATUS TINYINT NOT NULL DEFAULT 0 COMMENT '진행 상태 (0: 미진행, 1: 진행중, 2: 완료)',
    COMPLETED_AT TIMESTAMP NULL DEFAULT NULL COMMENT '완료일시',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX)
) COMMENT='사용자 퀘스트';

CREATE TABLE MODERATION_LOG (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '검증 로그 순번',
    TARGET_TYPE TINYINT NOT NULL COMMENT '검증 대상 (1: 스팟 게시글, 2: 댓글)',
    TARGET_IDX INT NOT NULL COMMENT '검증 대상 순번',
    PROVIDER VARCHAR(30) NOT NULL COMMENT '검증 제공자 (VISION_API, MODERATION_API)',
    RESULT TINYINT NOT NULL COMMENT '검증 결과 (0: 실패, 1: 성공)',
    RAW_SCORE JSON DEFAULT NULL COMMENT 'AI 검증 결과 원본(JSON)',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    PRIMARY KEY (IDX)
) COMMENT='AI 검증 로그';

CREATE TABLE CHARACTER_MASTER_I18N (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '번역 순번',
    CHARACTER_IDX INT NOT NULL COMMENT '캐릭터 순번',
    LANGUAGE_CODE VARCHAR(10) NOT NULL COMMENT '언어 코드(ko, en, ja, zh)',
    CHARACTER_NAME VARCHAR(100) NOT NULL COMMENT '캐릭터명',
    CHARACTER_DESCRIPTION VARCHAR(500) DEFAULT NULL COMMENT '캐릭터 설명',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX),
    UNIQUE KEY UK_CHARACTER_I18N (CHARACTER_IDX, LANGUAGE_CODE)
) COMMENT='캐릭터 번역';

CREATE TABLE ITEM_I18N (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '번역 순번',
    ITEM_IDX INT NOT NULL COMMENT '아이템 순번',
    LANGUAGE_CODE VARCHAR(10) NOT NULL COMMENT '언어 코드(ko, en, ja, zh)',
    ITEM_NAME VARCHAR(100) NOT NULL COMMENT '아이템명',
    ITEM_DESCRIPTION VARCHAR(500) DEFAULT NULL COMMENT '아이템 설명',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX),
    UNIQUE KEY UK_ITEM_I18N (ITEM_IDX, LANGUAGE_CODE)
) COMMENT='아이템 번역';

CREATE TABLE CATEGORY_CONTENT_I18N (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '번역 순번',
    CATEGORY_CONTENT_IDX INT NOT NULL COMMENT '관광지 순번',
    LANGUAGE_CODE VARCHAR(10) NOT NULL COMMENT '언어 코드(ko, en, ja, zh)',
    NAME VARCHAR(200) NOT NULL COMMENT '관광지명',
    CONTENT TEXT DEFAULT NULL COMMENT '설명',
    OPERATING_HOURS VARCHAR(255) DEFAULT NULL COMMENT '운영시간',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX),
    UNIQUE KEY UK_CATEGORY_CONTENT_I18N (CATEGORY_CONTENT_IDX, LANGUAGE_CODE)
) COMMENT='관광지 번역';

CREATE TABLE COURSE_I18N (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '번역 순번',
    COURSE_IDX INT NOT NULL COMMENT '코스 순번',
    LANGUAGE_CODE VARCHAR(10) NOT NULL COMMENT '언어 코드(ko, en, ja, zh)',
    COURSE_NAME VARCHAR(200) NOT NULL COMMENT '코스명',
    COURSE_DESCRIPTION TEXT DEFAULT NULL COMMENT '코스 설명',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX),
    UNIQUE KEY UK_COURSE_I18N (COURSE_IDX, LANGUAGE_CODE)
) COMMENT='코스 번역';

CREATE TABLE QUEST_I18N (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '번역 순번',
    QUEST_IDX INT NOT NULL COMMENT '퀘스트 순번',
    LANGUAGE_CODE VARCHAR(10) NOT NULL COMMENT '언어 코드(ko, en, ja, zh)',
    QUEST_NAME VARCHAR(200) NOT NULL COMMENT '퀘스트명',
    QUEST_DESCRIPTION TEXT DEFAULT NULL COMMENT '퀘스트 설명',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX),
    UNIQUE KEY UK_QUEST_I18N (QUEST_IDX, LANGUAGE_CODE)
) COMMENT='퀘스트 번역';

CREATE TABLE POPUP_I18N (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '번역 순번',
    POPUP_IDX INT NOT NULL COMMENT '팝업 순번',
    LANGUAGE_CODE VARCHAR(10) NOT NULL COMMENT '언어 코드(ko, en, ja, zh)',
    TITLE VARCHAR(300) NOT NULL COMMENT '제목',
    CONTENT TEXT DEFAULT NULL COMMENT '내용',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX),
    UNIQUE KEY UK_POPUP_I18N (POPUP_IDX, LANGUAGE_CODE)
) COMMENT='팝업 번역';

CREATE TABLE FESTIVAL_I18N (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '번역 순번',
    FESTIVAL_IDX INT NOT NULL COMMENT '축제 순번',
    LANGUAGE_CODE VARCHAR(10) NOT NULL COMMENT '언어 코드(ko, en, ja, zh)',
    NAME VARCHAR(300) NOT NULL COMMENT '축제명',
    CONTENT TEXT DEFAULT NULL COMMENT '축제 설명',
    LOCATION VARCHAR(300) DEFAULT NULL COMMENT '장소',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX),
    UNIQUE KEY UK_FESTIVAL_I18N (FESTIVAL_IDX, LANGUAGE_CODE)
) COMMENT='축제 번역';

CREATE TABLE MAP_PLACE (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '장소 순번',
    PLACE_IDX INT NOT NULL COMMENT '관광지/맛집 IDX',
    PLACE_CODE VARCHAR(50) NOT NULL COMMENT '장소 코드',
    MARKER_ICON_TYPE VARCHAR(30) NOT NULL COMMENT '마커 아이콘',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX)
) COMMENT='지도 장소';
