CREATE TABLE IF NOT EXISTS USERS (
    NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID VARCHAR(100) NOT NULL,
    NICKNAME VARCHAR(100) NOT NULL,
    COUNTRY VARCHAR(10) NOT NULL,
    BIRTH_DATE DATE NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PROFILE_IMAGE VARCHAR(800) NULL,
    STATUS TINYINT NOT NULL DEFAULT 1,
    LANGUAGE_CODE VARCHAR(10) NOT NULL DEFAULT 'ko',
    LAST_VISITED_AT DATETIME NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT DATETIME NULL,
    UNIQUE KEY UK_USERS_ID (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PLACE (
    IDX BIGINT AUTO_INCREMENT PRIMARY KEY,
    SOURCE VARCHAR(50) NULL,
    CONTENT_ID VARCHAR(100) NULL,
    TYPE VARCHAR(20) NOT NULL DEFAULT 'TOUR',
    NAME VARCHAR(200) NULL,
    TEXT TEXT NULL,
    CONTENT TEXT NULL,
    IMG VARCHAR(600) NULL,
    ADDRESS VARCHAR(500) NULL,
    LATITUDE VARCHAR(50) NULL,
    LONGITUDE VARCHAR(50) NULL,
    OPERATING_HOURS VARCHAR(300) NULL,
    ADMISSION_FEE VARCHAR(300) NULL,
    PARKING VARCHAR(300) NULL,
    IS_DISPLAY TINYINT NOT NULL DEFAULT 1,
    IS_RECOMMENDED TINYINT NOT NULL DEFAULT 0,
    VIEW_COUNT INT NOT NULL DEFAULT 0,
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY UK_PLACE_SOURCE_CONTENT (SOURCE, CONTENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS FESTIVAL (
    IDX BIGINT AUTO_INCREMENT PRIMARY KEY,
    SOURCE VARCHAR(50) NULL,
    CONTENT_ID VARCHAR(100) NULL,
    NAME VARCHAR(300) NULL,
    CONTENT TEXT NULL,
    LOCATION VARCHAR(500) NULL,
    START_DATE DATETIME NULL,
    IMG VARCHAR(600) NULL,
    URL VARCHAR(600) NULL,
    IS_TRASH TINYINT NOT NULL DEFAULT 0,
    END_DATE DATETIME NULL,
    UNIQUE KEY UK_FESTIVAL_SOURCE_CONTENT (SOURCE, CONTENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PLACE_I18N (
    IDX BIGINT AUTO_INCREMENT PRIMARY KEY,
    PLACE_IDX BIGINT NOT NULL,
    LANGUAGE_CODE VARCHAR(10) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    TEXT TEXT NULL,
    ADDRESS VARCHAR(500) NULL,
    OPERATING_HOURS VARCHAR(300) NULL,
    ADMISSION_FEE VARCHAR(300) NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UK_PLACE_I18N (PLACE_IDX, LANGUAGE_CODE),
    CONSTRAINT FK_PLACE_I18N_PLACE FOREIGN KEY (PLACE_IDX) REFERENCES PLACE(IDX) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS FESTIVAL_I18N (
    IDX BIGINT AUTO_INCREMENT PRIMARY KEY,
    FESTIVAL_IDX BIGINT NOT NULL,
    LANGUAGE_CODE VARCHAR(10) NOT NULL,
    NAME VARCHAR(300) NOT NULL,
    CONTENT TEXT NULL,
    LOCATION VARCHAR(500) NULL,
    UNIQUE KEY UK_FESTIVAL_I18N (FESTIVAL_IDX, LANGUAGE_CODE),
    CONSTRAINT FK_FESTIVAL_I18N_FESTIVAL FOREIGN KEY (FESTIVAL_IDX) REFERENCES FESTIVAL(IDX) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS MAIN_BANNER (
    IDX BIGINT AUTO_INCREMENT PRIMARY KEY,
    IMG VARCHAR(800) NULL,
    START_DATE DATETIME NULL,
    END_DATE DATETIME NULL,
    IS_DISPLAY TINYINT NOT NULL DEFAULT 0,
    IS_TRASH TINYINT NOT NULL DEFAULT 0,
    LINK VARCHAR(800) NULL,
    SORT INT NOT NULL DEFAULT 0,
    TITLE VARCHAR(300) NULL,
    SUB_TITLE VARCHAR(200) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS POPUP (
    IDX BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(1000) NULL,
    CONTENT TEXT NULL,
    IMG VARCHAR(500) NULL,
    LINK VARCHAR(500) NULL,
    START_DATE DATETIME NULL,
    END_DATE DATETIME NULL,
    IS_DISPLAY TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS POPUP_I18N (
    IDX BIGINT AUTO_INCREMENT PRIMARY KEY,
    POPUP_IDX BIGINT NOT NULL,
    LANGUAGE_CODE VARCHAR(10) NOT NULL,
    TITLE VARCHAR(300) NOT NULL,
    CONTENT TEXT NULL,
    UNIQUE KEY UK_POPUP_I18N (POPUP_IDX, LANGUAGE_CODE),
    CONSTRAINT FK_POPUP_I18N_POPUP FOREIGN KEY (POPUP_IDX) REFERENCES POPUP(IDX) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SPOTS (
    IDX BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_NO BIGINT NOT NULL,
    MAP_PROVIDER VARCHAR(20) NOT NULL DEFAULT 'KAKAO',
    MAP_PLACE_ID VARCHAR(100) NOT NULL,
    PLACE_TYPE VARCHAR(20) NOT NULL DEFAULT 'TOUR',
    PLACE_NAME VARCHAR(200) NOT NULL,
    PLACE_ADDRESS VARCHAR(500) NULL,
    LAT DECIMAL(10, 7) NOT NULL,
    LNG DECIMAL(10, 7) NOT NULL,
    PHOTO_URL VARCHAR(800) NULL,
    CAPTION VARCHAR(350) NULL,
    LIKE_COUNT INT NOT NULL DEFAULT 0,
    MODERATION_STATUS TINYINT NOT NULL DEFAULT 0,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT DATETIME NULL,
    KEY IX_SPOTS_USER_CREATED (USER_NO, CREATED_AT),
    KEY IX_SPOTS_PROVIDER_PLACE (MAP_PROVIDER, MAP_PLACE_ID),
    KEY IX_SPOTS_RANKING (MODERATION_STATUS, DELETED_AT, LIKE_COUNT, CREATED_AT),
    CONSTRAINT FK_SPOTS_USERS FOREIGN KEY (USER_NO) REFERENCES USERS(NO) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SPOT_RANKING_RUN (
    RANK_DATE DATE PRIMARY KEY,
    UPDATED_AT DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SPOT_RANKING_DAILY (
    RANK_DATE DATE NOT NULL,
    SPOT_IDX BIGINT NOT NULL,
    RANK_POSITION INT NOT NULL,
    LIKE_COUNT INT NOT NULL,
    PRIMARY KEY (RANK_DATE, SPOT_IDX),
    UNIQUE KEY UK_SPOT_RANKING_POSITION (RANK_DATE, RANK_POSITION),
    CONSTRAINT FK_SPOT_RANKING_SPOTS FOREIGN KEY (SPOT_IDX) REFERENCES SPOTS(IDX) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SPOT_COMMENT (
    IDX BIGINT AUTO_INCREMENT PRIMARY KEY,
    SPOT_IDX BIGINT NOT NULL,
    USER_NO BIGINT NOT NULL,
    CONTENT TEXT NOT NULL,
    MODERATION_STATUS TINYINT NOT NULL DEFAULT 0,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT DATETIME NULL,
    KEY IX_SPOT_COMMENT_SPOT_CREATED (SPOT_IDX, CREATED_AT, IDX),
    CONSTRAINT FK_SPOT_COMMENT_SPOTS FOREIGN KEY (SPOT_IDX) REFERENCES SPOTS(IDX) ON DELETE CASCADE,
    CONSTRAINT FK_SPOT_COMMENT_USERS FOREIGN KEY (USER_NO) REFERENCES USERS(NO) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SPOT_REACTIONS (
    IDX BIGINT AUTO_INCREMENT PRIMARY KEY,
    SPOT_IDX BIGINT NOT NULL,
    USER_NO BIGINT NOT NULL,
    TYPE TINYINT NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY UK_SPOT_REACTION (SPOT_IDX, USER_NO, TYPE),
    CONSTRAINT FK_SPOT_REACTIONS_SPOTS FOREIGN KEY (SPOT_IDX) REFERENCES SPOTS(IDX) ON DELETE CASCADE,
    CONSTRAINT FK_SPOT_REACTIONS_USERS FOREIGN KEY (USER_NO) REFERENCES USERS(NO) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS MODERATION_LOG (
    IDX BIGINT AUTO_INCREMENT PRIMARY KEY,
    TARGET_TYPE TINYINT NOT NULL,
    TARGET_IDX BIGINT NOT NULL,
    PROVIDER VARCHAR(50) NOT NULL,
    RESULT TINYINT NOT NULL,
    RAW_SCORE TEXT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS NOTIFICATION (
    IDX BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_NO BIGINT NOT NULL,
    TYPE VARCHAR(30) NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    MESSAGE VARCHAR(500) NOT NULL,
    TARGET_TYPE VARCHAR(30) NULL,
    TARGET_IDX BIGINT NULL,
    IS_READ TINYINT NOT NULL DEFAULT 0,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    READ_AT DATETIME NULL,
    KEY IX_NOTIFICATION_USER_READ_CREATED (USER_NO, IS_READ, CREATED_AT),
    CONSTRAINT FK_NOTIFICATION_USERS FOREIGN KEY (USER_NO) REFERENCES USERS(NO) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =====================================================================
-- 2) 게임/확장 테이블 (추가 설계 - 아직 백엔드 미연동)
--    USERS 를 참조하는 FK 는 USERS.NO(BIGINT) 에 맞춰 USER_NO 를 BIGINT 로 둠.
-- =====================================================================

CREATE TABLE IF NOT EXISTS CHARACTER_MASTER (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '캐릭터 순번',
    CHARACTER_TYPE VARCHAR(100) NOT NULL COMMENT '캐릭터 타입 (1: 승려, 2: 궁녀, 3: 왕, 4: 상인, 5: 무사)',
    IMAGE_URL VARCHAR(255) DEFAULT NULL COMMENT '캐릭터 이미지',
    IS_ACTIVE TINYINT NOT NULL DEFAULT 1 COMMENT '사용 여부 (0: 미사용, 1: 사용)',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    PRIMARY KEY (IDX)
) COMMENT='캐릭터';

CREATE TABLE IF NOT EXISTS ITEM (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '아이템 IDX',
    ITEM_NAME VARCHAR(100) NOT NULL COMMENT '아이템명',
    ITEM_TYPE TINYINT NOT NULL COMMENT '아이템 종류 (1: 모자, 2: 상의, 3: 하의, 4: 신발, 5: 무기, 6: 장신구)',
    CHARACTER_IDX INT NOT NULL COMMENT '착용 가능 캐릭터 IDX',
    ITEM_IMAGE VARCHAR(255) DEFAULT NULL COMMENT '아이템 이미지',
    ITEM_MODEL_IMAGE VARCHAR(255) DEFAULT NULL COMMENT '아이템 모델 이미지',
    ITEM_DESCRIPTION VARCHAR(500) DEFAULT NULL COMMENT '아이템 설명',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    PRIMARY KEY (IDX)
) COMMENT='아이템 마스터 테이블';

CREATE TABLE IF NOT EXISTS USER_AUTH (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '인증 정보 순번',
    USER_NO BIGINT NOT NULL COMMENT '사용자 고유 NO',
    PASSWORD_HASH VARCHAR(255) DEFAULT NULL COMMENT '비밀번호 해시',
    PROVIDER TINYINT NOT NULL DEFAULT 1 COMMENT '로그인 방식 (1: 일반, 2: Google, 3: Kakao, 4: Naver)',
    PROVIDER_ID VARCHAR(255) DEFAULT NULL COMMENT '소셜 로그인 제공자 사용자 ID',
    EMAIL_VERIFIED TINYINT NOT NULL DEFAULT 0 COMMENT '이메일 인증 여부 (0: 미인증, 1: 인증)',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    PRIMARY KEY (IDX),
    CONSTRAINT FK_USER_AUTH_USERS FOREIGN KEY (USER_NO) REFERENCES USERS(NO) ON DELETE CASCADE
) COMMENT='사용자 인증 정보 테이블';

CREATE TABLE IF NOT EXISTS USER_CHARACTER (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '사용자 캐릭터 순번',
    USER_NO BIGINT NOT NULL COMMENT '사용자 순번',
    CHARACTER_IDX INT NOT NULL COMMENT '착용 가능 캐릭터 IDX',
    IS_SELECTED TINYINT NOT NULL DEFAULT 0 COMMENT '대표 캐릭터 여부 (0: 미선택, 1: 선택)',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    PRIMARY KEY (IDX),
    CONSTRAINT FK_USER_CHARACTER_USERS FOREIGN KEY (USER_NO) REFERENCES USERS(NO) ON DELETE CASCADE
) COMMENT='사용자 캐릭터 테이블';

CREATE TABLE IF NOT EXISTS USER_ITEM (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '사용자 아이템 순번',
    USER_NO BIGINT NOT NULL COMMENT '사용자 고유 NO',
    USER_CHARACTER_IDX INT NOT NULL COMMENT '사용자 캐릭터 순번 USER_CARACTER IDX',
    ITEM_IDX INT NOT NULL COMMENT '아이템 순번 ITEM IDX',
    IS_EQUIPPED TINYINT NOT NULL DEFAULT 0 COMMENT '착용 여부 (0: 미착용, 1: 착용)',
    ACQUIRED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '획득일시',
    PRIMARY KEY (IDX)
) COMMENT='사용자 아이템 테이블';

CREATE TABLE IF NOT EXISTS CATEGORY (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '인덱스',
    TYPE VARCHAR(100) NOT NULL COMMENT '종류 (TOUR, FOOD)',
    CATEGORY_DIV VARCHAR(100) NOT NULL COMMENT '구분 (TOUR: 문화재 자연 , FOOD: 한식 카페)',
    CONTENT VARCHAR(600) DEFAULT NULL COMMENT '설명',
    IS_DISPLAY TINYINT NOT NULL DEFAULT 0 COMMENT '전시여부 (0: 비노출, 1: 노출)',
    REG_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
    PRIMARY KEY (IDX)
) COMMENT='카테고리';

CREATE TABLE IF NOT EXISTS MAP_PLACE (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '장소 순번',
    PLACE_IDX INT NOT NULL COMMENT '관광지/맛집 IDX',
    PLACE_CODE VARCHAR(50) NOT NULL COMMENT '장소 코드',
    MARKER_ICON_TYPE VARCHAR(30) NOT NULL COMMENT '마커 아이콘',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX)
) COMMENT='지도 장소';

CREATE TABLE IF NOT EXISTS MAP_PLACE_DOCENT (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '도슨트 순번',
    MAP_PLACE_IDX INT NOT NULL COMMENT '장소 순번',
    LANGUAGE_CODE VARCHAR(10) NOT NULL COMMENT '언어 코드(ko, en, ja, zh)',
    TITLE VARCHAR(200) NOT NULL COMMENT '도슨트 제목',
    CONTENT TEXT NOT NULL COMMENT '도슨트 본문 내용',
    DESCRIPTION TEXT DEFAULT NULL COMMENT '도슨트 부가설명',
    AUDIO_URL VARCHAR(1000) DEFAULT NULL COMMENT '음성 파일 URL',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UNIQUE KEY UK_MAP_PLACE_LANGUAGE (MAP_PLACE_IDX, LANGUAGE_CODE),
    PRIMARY KEY (IDX)
) COMMENT='장소별 다국어 도슨트 정보';

CREATE TABLE IF NOT EXISTS COURSE (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '코스 IDX',
    USER_CHARACTER_IDX INT NOT NULL COMMENT '사용자 캐릭터 IDX',
    COURSE_NAME VARCHAR(100) NOT NULL COMMENT '코스명',
    DESCRIPTION VARCHAR(500) DEFAULT NULL COMMENT '코스 설명',
    COURSE_IMAGE VARCHAR(255) DEFAULT NULL COMMENT '코스 이미지',
    REWARD_IMAGE VARCHAR(500) NOT NULL DEFAULT 0 COMMENT '코스 완료 보상 이미지',
    IS_ACTIVE TINYINT NOT NULL DEFAULT 1 COMMENT '사용 여부 (0: 미사용, 1: 사용)',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX)
) COMMENT='코스';

CREATE TABLE IF NOT EXISTS QUEST (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '퀘스트 순번',
    COURSE_IDX INT NOT NULL COMMENT '코스 순번',
    MAP_PLACE_IDX INT NOT NULL COMMENT '장소 순번',
    QUEST_ORDER TINYINT NOT NULL COMMENT '퀘스트 순서',
    QUEST_TYPE TINYINT NOT NULL COMMENT '퀘스트 종류 (1: 방문, 2: 사진촬영, 3: 도슨트청취, 4: 퀴즈)',
    TITLE VARCHAR(200) NOT NULL COMMENT '퀘스트 제목',
    CONTENT TEXT DEFAULT NULL COMMENT '퀘스트 설명',
    REWARD_ITEM_IDX INT DEFAULT NULL COMMENT '퀘스트 보상 아이템 ITEM IDX',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX)
) COMMENT='퀘스트';

CREATE TABLE IF NOT EXISTS USER_QUEST (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '사용자 퀘스트 순번',
    USER_CHARACTER_IDX INT NOT NULL COMMENT '사용자 캐릭터 순번',
    QUEST_IDX INT NOT NULL COMMENT '퀘스트 순번',
    STATUS TINYINT NOT NULL DEFAULT 0 COMMENT '진행 상태 (0: 미진행, 1: 진행중, 2: 완료)',
    COMPLETED_AT TIMESTAMP NULL DEFAULT NULL COMMENT '완료일시',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX)
) COMMENT='사용자 퀘스트';

CREATE TABLE IF NOT EXISTS CHARACTER_MASTER_I18N (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '번역 순번',
    CHARACTER_IDX INT NOT NULL COMMENT '캐릭터 순번',
    LANGUAGE_CODE VARCHAR(10) NOT NULL COMMENT '언어 코드(ko, en, ja, zh)',
    CHARACTER_NAME VARCHAR(100) NOT NULL COMMENT '캐릭터명',
    CHARACTER_DESCRIPTION VARCHAR(500) DEFAULT NULL COMMENT '캐릭터 설명',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX),
    UNIQUE KEY UK_CHARACTER_I18N (CHARACTER_IDX, LANGUAGE_CODE)
) COMMENT='캐릭터 번역';

CREATE TABLE IF NOT EXISTS ITEM_I18N (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '번역 순번',
    ITEM_IDX INT NOT NULL COMMENT '아이템 순번',
    LANGUAGE_CODE VARCHAR(10) NOT NULL COMMENT '언어 코드(ko, en, ja, zh)',
    ITEM_NAME VARCHAR(100) NOT NULL COMMENT '아이템명',
    ITEM_DESCRIPTION VARCHAR(500) DEFAULT NULL COMMENT '아이템 설명',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX),
    UNIQUE KEY UK_ITEM_I18N (ITEM_IDX, LANGUAGE_CODE)
) COMMENT='아이템 번역';

CREATE TABLE IF NOT EXISTS CATEGORY_CONTENT_I18N (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '번역 순번',
    CATEGORY_CONTENT_IDX INT NOT NULL COMMENT '관광지 순번',
    LANGUAGE_CODE VARCHAR(10) NOT NULL COMMENT '언어 코드(ko, en, ja, zh)',
    NAME VARCHAR(200) NOT NULL COMMENT '관광지명',
    CONTENT TEXT DEFAULT NULL COMMENT '설명',
    OPERATING_HOURS VARCHAR(255) DEFAULT NULL COMMENT '운영시간',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX),
    UNIQUE KEY UK_CATEGORY_CONTENT_I18N (CATEGORY_CONTENT_IDX, LANGUAGE_CODE)
) COMMENT='관광지 번역';

CREATE TABLE IF NOT EXISTS COURSE_I18N (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '번역 순번',
    COURSE_IDX INT NOT NULL COMMENT '코스 순번',
    LANGUAGE_CODE VARCHAR(10) NOT NULL COMMENT '언어 코드(ko, en, ja, zh)',
    COURSE_NAME VARCHAR(200) NOT NULL COMMENT '코스명',
    COURSE_DESCRIPTION TEXT DEFAULT NULL COMMENT '코스 설명',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX),
    UNIQUE KEY UK_COURSE_I18N (COURSE_IDX, LANGUAGE_CODE)
) COMMENT='코스 번역';

CREATE TABLE IF NOT EXISTS QUEST_I18N (
    IDX INT NOT NULL AUTO_INCREMENT COMMENT '번역 순번',
    QUEST_IDX INT NOT NULL COMMENT '퀘스트 순번',
    LANGUAGE_CODE VARCHAR(10) NOT NULL COMMENT '언어 코드(ko, en, ja, zh)',
    QUEST_NAME VARCHAR(200) NOT NULL COMMENT '퀘스트명',
    QUEST_DESCRIPTION TEXT DEFAULT NULL COMMENT '퀘스트 설명',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (IDX),
    UNIQUE KEY UK_QUEST_I18N (QUEST_IDX, LANGUAGE_CODE)
) COMMENT='퀘스트 번역';


-- 로컬 개발용 기본 사용자 (백엔드가 NO=1 을 사용)
INSERT INTO USERS (NO, ID, NICKNAME, COUNTRY, EMAIL, LANGUAGE_CODE)
VALUES (1, 'local-development-user', 'lotus_traveler', 'KR', 'traveler@example.com', 'ko')
ON DUPLICATE KEY UPDATE NO = NO;

INSERT INTO CHARACTER_MASTER (CHARACTER_TYPE, IMAGE_URL, IS_ACTIVE)
SELECT 'DONGGYEONG', NULL, 1
WHERE NOT EXISTS (
    SELECT 1 FROM CHARACTER_MASTER WHERE CHARACTER_TYPE = 'DONGGYEONG'
);

INSERT INTO ITEM (
    ITEM_NAME, ITEM_TYPE, CHARACTER_IDX, ITEM_IMAGE, ITEM_MODEL_IMAGE, ITEM_DESCRIPTION
)
SELECT seed.ITEM_NAME, seed.ITEM_TYPE, character_row.IDX, NULL, NULL, seed.ITEM_DESCRIPTION
FROM (
    SELECT '금관' AS ITEM_NAME, 1 AS ITEM_TYPE, '신라 금관을 본뜬 머리 장식' AS ITEM_DESCRIPTION
    UNION ALL SELECT '연꽃 장식', 6, '동경이 목에 착용하는 연꽃 장식'
    UNION ALL SELECT '청록 두루마기', 2, '동경이 전용 청록색 의상'
    UNION ALL SELECT '여행 카메라', 5, '여행 기록을 남기는 손 착용 아이템'
    UNION ALL SELECT '천년 등불', 5, '야간 여행을 밝히는 손 착용 아이템'
) seed
JOIN CHARACTER_MASTER character_row ON character_row.CHARACTER_TYPE = 'DONGGYEONG'
WHERE NOT EXISTS (
    SELECT 1
    FROM ITEM existing
    WHERE existing.CHARACTER_IDX = character_row.IDX
      AND existing.ITEM_NAME = seed.ITEM_NAME
);
