CREATE TABLE IF NOT EXISTS USERS (
    NO INTEGER PRIMARY KEY AUTOINCREMENT,
    ID TEXT NOT NULL,
    NICKNAME TEXT NOT NULL,
    COUNTRY TEXT NOT NULL,
    BIRTH_DATE TEXT,
    EMAIL TEXT NOT NULL,
    PROFILE_IMAGE TEXT,
    STATUS INTEGER NOT NULL DEFAULT 1 CHECK (STATUS IN (1, 2, 3)),
    LANGUAGE_CODE TEXT NOT NULL DEFAULT 'ko',
    LAST_VISITED_AT TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TEXT,
    CONSTRAINT UK_USERS_ID UNIQUE (ID)
);

CREATE TABLE IF NOT EXISTS PLACE (
    IDX INTEGER PRIMARY KEY AUTOINCREMENT,
    SOURCE TEXT,
    CONTENT_ID TEXT,
    TYPE TEXT NOT NULL DEFAULT 'TOUR' CHECK (TYPE IN ('TOUR', 'FOOD')),
    NAME TEXT,
    TEXT TEXT,
    CONTENT TEXT,
    IMG TEXT,
    ADDRESS TEXT,
    LATITUDE TEXT,
    LONGITUDE TEXT,
    OPERATING_HOURS TEXT,
    ADMISSION_FEE TEXT,
    PARKING TEXT,
    IS_DISPLAY INTEGER NOT NULL DEFAULT 1 CHECK (IS_DISPLAY IN (0, 1)),
    IS_RECOMMENDED INTEGER NOT NULL DEFAULT 0 CHECK (IS_RECOMMENDED IN (0, 1)),
    VIEW_COUNT INTEGER NOT NULL DEFAULT 0,
    REG_DATE TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UK_PLACE_SOURCE_CONTENT UNIQUE (SOURCE, CONTENT_ID)
);

CREATE TABLE IF NOT EXISTS FESTIVAL (
    IDX INTEGER PRIMARY KEY AUTOINCREMENT,
    SOURCE TEXT,
    CONTENT_ID TEXT,
    NAME TEXT,
    CONTENT TEXT,
    LOCATION TEXT,
    START_DATE TEXT,
    IMG TEXT,
    URL TEXT,
    IS_TRASH INTEGER NOT NULL DEFAULT 0 CHECK (IS_TRASH IN (0, 1)),
    END_DATE TEXT,
    CONSTRAINT UK_FESTIVAL_SOURCE_CONTENT UNIQUE (SOURCE, CONTENT_ID)
);

CREATE TABLE IF NOT EXISTS PLACE_I18N (
    IDX INTEGER PRIMARY KEY AUTOINCREMENT,
    PLACE_IDX INTEGER NOT NULL,
    LANGUAGE_CODE TEXT NOT NULL,
    NAME TEXT NOT NULL,
    TEXT TEXT,
    ADDRESS TEXT,
    OPERATING_HOURS TEXT,
    ADMISSION_FEE TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UK_PLACE_I18N UNIQUE (PLACE_IDX, LANGUAGE_CODE),
    CONSTRAINT FK_PLACE_I18N_PLACE
        FOREIGN KEY (PLACE_IDX) REFERENCES PLACE(IDX) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FESTIVAL_I18N (
    IDX INTEGER PRIMARY KEY AUTOINCREMENT,
    FESTIVAL_IDX INTEGER NOT NULL,
    LANGUAGE_CODE TEXT NOT NULL,
    NAME TEXT NOT NULL,
    CONTENT TEXT,
    LOCATION TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UK_FESTIVAL_I18N UNIQUE (FESTIVAL_IDX, LANGUAGE_CODE),
    CONSTRAINT FK_FESTIVAL_I18N_FESTIVAL
        FOREIGN KEY (FESTIVAL_IDX) REFERENCES FESTIVAL(IDX) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CATEGORY_CONTENT_I18N (
    IDX INTEGER PRIMARY KEY AUTOINCREMENT,
    CATEGORY_CONTENT_IDX INTEGER NOT NULL,
    LANGUAGE_CODE TEXT NOT NULL,
    NAME TEXT NOT NULL,
    CONTENT TEXT,
    OPERATING_HOURS TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UK_CATEGORY_CONTENT_I18N
        UNIQUE (CATEGORY_CONTENT_IDX, LANGUAGE_CODE)
);

CREATE TABLE IF NOT EXISTS SPOTS (
    IDX INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_NO INTEGER NOT NULL,
    MAP_PLACE_ID TEXT,
    LAT NUMERIC NOT NULL CHECK (LAT BETWEEN -90 AND 90),
    LNG NUMERIC NOT NULL CHECK (LNG BETWEEN -180 AND 180),
    PHOTO_URL TEXT,
    CAPTION TEXT CHECK (length(CAPTION) <= 350),
    LIKE_COUNT INTEGER NOT NULL DEFAULT 0,
    MODERATION_STATUS INTEGER NOT NULL DEFAULT 0
        CHECK (MODERATION_STATUS IN (0, 1, 2)),
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TEXT,
    CONSTRAINT FK_SPOTS_USERS
        FOREIGN KEY (USER_NO) REFERENCES USERS(NO) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IX_SPOTS_USER_CREATED
    ON SPOTS (USER_NO, CREATED_AT DESC);

CREATE INDEX IF NOT EXISTS IX_SPOTS_PLACE
    ON SPOTS (MAP_PLACE_ID);

INSERT INTO USERS (
    NO,
    ID,
    NICKNAME,
    COUNTRY,
    EMAIL,
    LANGUAGE_CODE
)
VALUES (
    1,
    'local-development-user',
    'lotus_traveler',
    'KR',
    'traveler@example.com',
    'ko'
)
ON CONFLICT(NO) DO NOTHING;
